APPELLATIONS = {
  'Afghanistan' => [],
  'Albania' => [],
  'Algeria' => [],
  'American Samoa' => [],
  'Andorra' => [],
  'Angola' => [],
  'Anguilla' => [],
  'Antarctica' => [],
  'Antigua And Barbuda' => [],
  'Argentina' => [],
  'Armenia' => [],
  'Aruba' => [],
  'Australia' => [],
  'Austria' => [],
  'Azerbaijan' => [],
  'Bahamas' => [],
  'Bahrain' => [],
  'Bangladesh' => [],
  'Barbados' => [],
  'Belarus' => [],
  'Belgium' => [],
  'Belize' => [],
  'Benin' => [],
  'Bermuda' => [],
  'Bhutan' => [],
  'Bolivia' => [],
  'Bosnia And Herzegovina' => [],
  'Botswana' => [],
  'Bouvet Island' => [],
  'Brazil' => [],
  'British Indian Ocean Territory' => [],
  'Brunei Darussalam' => [],
  'Bulgaria' => [],
  'Burkina Faso' => [],
  'Burundi' => [],
  'Cambodia' => [],
  'Cameroon' => [],
  'Canada' => [],
  'Cape Verde' => [],
  'Cayman Islands' => [],
  'Central African Republic' => [],
  'Chad' => [],
  'Chile' => [],
  'China' => [],
  'Christmas Island' => [],
  'Cocos (Keeling) Islands' => [],
  'Colombia' => [],
  'Comoros' => [],
  'Congo' => [],
  'Congo, The Democratic Republic Of The' => [],
  'Cook Islands' => [],
  'Costa Rica' => [],
  'Cote d\'Ivoire' => [],
  'Croatia' => [],
  'Cuba' => [],
  'Cyprus' => [],
  'Czech Republic' => [],
  'Denmark' => [],
  'Djibouti' => [],
  'Dominica' => [],
  'Dominican Republic' => [],
  'East Timor' => [],
  'Ecuador' => [],
  'Egypt' => [],
  'El Salvador' => [],
  'Equatorial Guinea' => [],
  'Eritrea' => [],
  'Estonia' => [],
  'Ethiopia' => [],
  'Falkland Islands (Malvinas)' => [],
  'Faroe Islands' => [],
  'Fiji' => [],
  'Finland' => [],
  'France' => [],
  'French Guiana' => [],
  'French Polynesia' => [],
  'French Southern Territories' => [],
  'Gabon' => [],
  'Gambia' => [],
  'Georgia' => [],
  'Germany' => [],
  'Ghana' => [],
  'Gibraltar' => [],
  'Greece' => [],
  'Greenland' => [],
  'Grenada' => [],
  'Guadeloupe' => [],
  'Guam' => [],
  'Guatemala' => [],
  'Guinea' => [],
  'Guinea-Bissau' => [],
  'Guyana' => [],
  'Haiti' => [],
  'Heard Island And Mcdonald Islands' => [],
  'Holy See (Vatican City State)' => [],
  'Honduras' => [],
  'Hong Kong' => [],
  'Hungary' => [],
  'Iceland' => [],
  'India' => [],
  'Indonesia' => [],
  'Iran, Islamic Republic Of' => [],
  'Iraq' => [],
  'Ireland' => [],
  'Israel' => [],
  'Italy' => [],
  'Jamaica' => [],
  'Japan' => [],
  'Jordan' => [],
  'Kazakstan' => [],
  'Kenya' => [],
  'Kiribati' => [],
  'Korea, Democratic People\'s Republic Of' => [],
  'Korea, Republic Of' => [],
  'Kosovo' => [],
  'Kuwait' => [],
  'Kyrgyzstan' => [],
  'Lao People\'s Democratic Republic' => [],
  'Latvia' => [],
  'Lebanon' => [],
  'Lesotho' => [],
  'Liberia' => [],
  'Libyan Arab Jamahiriya' => [],
  'Liechtenstein' => [],
  'Lithuania' => [],
  'Luxembourg' => [],
  'Macau' => [],
  'Macedonia, The Former Yugoslav Republic Of' => [],
  'Madagascar' => [],
  'Malawi' => [],
  'Malaysia' => [],
  'Maldives' => [],
  'Mali' => [],
  'Malta' => [],
  'Marshall Islands' => [],
  'Martinique' => [],
  'Mauritania' => [],
  'Mauritius' => [],
  'Mayotte' => [],
  'Mexico' => [],
  'Micronesia, Federated States Of' => [],
  'Moldova, Republic Of' => [],
  'Monaco' => [],
  'Mongolia' => [],
  'Montserrat' => [],
  'Montenegro' => [],
  'Morocco' => [],
  'Mozambique' => [],
  'Myanmar' => [],
  'Namibia' => [],
  'Nauru' => [],
  'Nepal' => [],
  'Netherlands' => [],
  'Netherlands Antilles' => [],
  'New Caledonia' => [],
  'New Zealand' => [],
  'Nicaragua' => [],
  'Niger' => [],
  'Nigeria' => [],
  'Niue' => [],
  'Norfolk Island' => [],
  'Northern Mariana Islands' => [],
  'Norway' => [],
  'Oman' => [],
  'Pakistan' => [],
  'Palau' => [],
  'Palestinian Territory, Occupied' => [],
  'Panama' => [],
  'Papua New Guinea' => [],
  'Paraguay' => [],
  'Peru' => [],
  'Philippines' => [],
  'Pitcairn' => [],
  'Poland' => [],
  'Portugal' => [],
  'Puerto Rico' => [],
  'Qatar' => [],
  'Reunion' => [],
  'Romania' => [],
  'Russian Federation' => [],
  'Rwanda' => [],
  'Saint Helena' => [],
  'Saint Kitts And Nevis' => [],
  'Saint Lucia' => [],
  'Saint Pierre And Miquelon' => [],
  'Saint Vincent And The Grenadines' => [],
  'Samoa' => [],
  'San Marino' => [],
  'Sao Tome And Principe' => [],
  'Saudi Arabia' => [],
  'Senegal' => [],
  'Serbia' => [],
  'Seychelles' => [],
  'Sierra Leone' => [],
  'Singapore' => [],
  'Slovakia' => [],
  'Slovenia' => [],
  'Solomon Islands' => [],
  'Somalia' => [],
  'South Africa' => [],
  'South Georgia And The South Sandwich Islands' => [],
  'Spain' => [],
  'Sri Lanka' => [],
  'Sudan' => [],
  'Suriname' => [],
  'Svalbard And Jan Mayen' => [],
  'Swaziland' => [],
  'Sweden' => [],
  'Switzerland' => [],
  'Syrian Arab Republic' => [],
  'Taiwan, Province Of China' => [],
  'Tajikistan' => [],
  'Tanzania, United Republic Of' => [],
  'Thailand' => [],
  'Togo' => [],
  'Tokelau' => [],
  'Tonga' => [],
  'Trinidad And Tobago' => [],
  'Tunisia' => [],
  'Turkey' => [],
  'Turkmenistan' => [],
  'Turks And Caicos Islands' => [],
  'Tuvalu' => [],
  'Uganda' => [],
  'Ukraine' => [],
  'United Arab Emirates' => [],
  'United Kingdom' => [],
  'United States' => [],
  'United States Minor Outlying Islands' => [],
  'Uruguay' => [],
  'Uzbekistan' => [],
  'Vanuatu' => [],
  'Venezuela' => [],
  'Vietnam' => [],
  'Virgin Islands, British' => [],
  'Virgin Islands, U.S.' => [],
  'Wallis And Futuna' => [],
  'Western Sahara' => [],
  'Yemen' => [],
  'Zambia' => [],
  'Zimbabwe' => []
}


REGIONS = [
  ['AF', 'Afghanistan'],
  ['AL', 'Albania'],
  ['DZ', 'Algeria'],
  ['AS', 'American Samoa'],
  ['AD', 'Andorra'],
  ['AO', 'Angola'],
  ['AI', 'Anguilla'],
  ['AQ', 'Antarctica'],
  ['AG', 'Antigua And Barbuda'],
  ['AR', 'Argentina'],
  ['AM', 'Armenia'],
  ['AW', 'Aruba'],
  ['AU', 'Australia'],
  ['AT', 'Austria'],
  ['AZ', 'Azerbaijan'],
  ['BS', 'Bahamas'],
  ['BH', 'Bahrain'],
  ['BD', 'Bangladesh'],
  ['BB', 'Barbados'],
  ['BY', 'Belarus'],
  ['BE', 'Belgium'],
  ['BZ', 'Belize'],
  ['BJ', 'Benin'],
  ['BM', 'Bermuda'],
  ['BT', 'Bhutan'],
  ['BO', 'Bolivia'],
  ['BA', 'Bosnia And Herzegovina'],
  ['BW', 'Botswana'],
  ['BV', 'Bouvet Island'],
  ['BR', 'Brazil'],
  ['IO', 'British Indian Ocean Territory'],
  ['BN', 'Brunei Darussalam'],
  ['BG', 'Bulgaria'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['KH', 'Cambodia'],
  ['CM', 'Cameroon'],
  ['CA', 'Canada'],
  ['CV', 'Cape Verde'],
  ['KY', 'Cayman Islands'],
  ['CF', 'Central African Republic'],
  ['TD', 'Chad'],
  ['CL', 'Chile'],
  ['CN', 'China'],
  ['CX', 'Christmas Island'],
  ['CC', 'Cocos (Keeling) Islands'],
  ['CO', 'Colombia'],
  ['KM', 'Comoros'],
  ['CG', 'Congo'],
  ['CD', 'Congo, The Democratic Republic Of The'],
  ['CK', 'Cook Islands'],
  ['CR', 'Costa Rica'],
  ['CI', 'Cote d\'Ivoire'],
  ['HR', 'Croatia'],
  ['CU', 'Cuba'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czech Republic'],
  ['DK', 'Denmark'],
  ['DJ', 'Djibouti'],
  ['DM', 'Dominica'],
  ['DO', 'Dominican Republic'],
  ['TP', 'East Timor'],
  ['EC', 'Ecuador'],
  ['EG', 'Egypt'],
  ['SV', 'El Salvador'],
  ['GQ', 'Equatorial Guinea'],
  ['ER', 'Eritrea'],
  ['EE', 'Estonia'],
  ['ET', 'Ethiopia'],
  ['FK', 'Falkland Islands (Malvinas)'],
  ['FO', 'Faroe Islands'],
  ['FJ', 'Fiji'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GF', 'French Guiana'],
  ['PF', 'French Polynesia'],
  ['TF', 'French Southern Territories'],
  ['GA', 'Gabon'],
  ['GM', 'Gambia'],
  ['GE', 'Georgia'],
  ['DE', 'Germany'],
  ['GH', 'Ghana'],
  ['GI', 'Gibraltar'],
  ['GR', 'Greece'],
  ['GL', 'Greenland'],
  ['GD', 'Grenada'],
  ['GP', 'Guadeloupe'],
  ['GU', 'Guam'],
  ['GT', 'Guatemala'],
  ['GN', 'Guinea'],
  ['GW', 'Guinea-Bissau'],
  ['GY', 'Guyana'],
  ['HT', 'Haiti'],
  ['HM', 'Heard Island And Mcdonald Islands'],
  ['VA', 'Holy See (Vatican City State)'],
  ['HN', 'Honduras'],
  ['HK', 'Hong Kong'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['IN', 'India'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran, Islamic Republic Of'],
  ['IQ', 'Iraq'],
  ['IE', 'Ireland'],
  ['IL', 'Israel'],
  ['IT', 'Italy'],
  ['JM', 'Jamaica'],
  ['JP', 'Japan'],
  ['JO', 'Jordan'],
  ['KZ', 'Kazakstan'],
  ['KE', 'Kenya'],
  ['KI', 'Kiribati'],
  ['KP', 'Korea, Democratic People\'s Republic Of'],
  ['KR', 'Korea, Republic Of'],
  ['KV', 'Kosovo'],
  ['KW', 'Kuwait'],
  ['KG', 'Kyrgyzstan'],
  ['LA', 'Lao People\'s Democratic Republic'],
  ['LV', 'Latvia'],
  ['LB', 'Lebanon'],
  ['LS', 'Lesotho'],
  ['LR', 'Liberia'],
  ['LY', 'Libyan Arab Jamahiriya'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MO', 'Macau'],
  ['MK', 'Macedonia, The Former Yugoslav Republic Of'],
  ['MG', 'Madagascar'],
  ['MW', 'Malawi'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['ML', 'Mali'],
  ['MT', 'Malta'],
  ['MH', 'Marshall Islands'],
  ['MQ', 'Martinique'],
  ['MR', 'Mauritania'],
  ['MU', 'Mauritius'],
  ['YT', 'Mayotte'],
  ['MX', 'Mexico'],
  ['FM', 'Micronesia, Federated States Of'],
  ['MD', 'Moldova, Republic Of'],
  ['MC', 'Monaco'],
  ['MN', 'Mongolia'],
  ['MS', 'Montserrat'],
  ['ME', 'Montenegro'],
  ['MA', 'Morocco'],
  ['MZ', 'Mozambique'],
  ['MM', 'Myanmar'],
  ['NA', 'Namibia'],
  ['NR', 'Nauru'],
  ['NP', 'Nepal'],
  ['NL', 'Netherlands'],
  ['AN', 'Netherlands Antilles'],
  ['NC', 'New Caledonia'],
  ['NZ', 'New Zealand'],
  ['NI', 'Nicaragua'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['NU', 'Niue'],
  ['NF', 'Norfolk Island'],
  ['MP', 'Northern Mariana Islands'],
  ['NO', 'Norway'],
  ['OM', 'Oman'],
  ['PK', 'Pakistan'],
  ['PW', 'Palau'],
  ['PS', 'Palestinian Territory, Occupied'],
  ['PA', 'Panama'],
  ['PG', 'Papua New Guinea'],
  ['PY', 'Paraguay'],
  ['PE', 'Peru'],
  ['PH', 'Philippines'],
  ['PN', 'Pitcairn'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['PR', 'Puerto Rico'],
  ['QA', 'Qatar'],
  ['RE', 'Reunion'],
  ['RO', 'Romania'],
  ['RU', 'Russian Federation'],
  ['RW', 'Rwanda'],
  ['SH', 'Saint Helena'],
  ['KN', 'Saint Kitts And Nevis'],
  ['LC', 'Saint Lucia'],
  ['PM', 'Saint Pierre And Miquelon'],
  ['VC', 'Saint Vincent And The Grenadines'],
  ['WS', 'Samoa'],
  ['SM', 'San Marino'],
  ['ST', 'Sao Tome And Principe'],
  ['SA', 'Saudi Arabia'],
  ['SN', 'Senegal'],
  ['RS', 'Serbia'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SG', 'Singapore'],
  ['SK', 'Slovakia'],
  ['SI', 'Slovenia'],
  ['SB', 'Solomon Islands'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa'],
  ['GS', 'South Georgia And The South Sandwich Islands'],
  ['ES', 'Spain'],
  ['LK', 'Sri Lanka'],
  ['SD', 'Sudan'],
  ['SR', 'Suriname'],
  ['SJ', 'Svalbard And Jan Mayen'],
  ['SZ', 'Swaziland'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland'],
  ['SY', 'Syrian Arab Republic'],
  ['TW', 'Taiwan, Province Of China'],
  ['TJ', 'Tajikistan'],
  ['TZ', 'Tanzania, United Republic Of'],
  ['TH', 'Thailand'],
  ['TG', 'Togo'],
  ['TK', 'Tokelau'],
  ['TO', 'Tonga'],
  ['TT', 'Trinidad And Tobago'],
  ['TN', 'Tunisia'],
  ['TR', 'Turkey'],
  ['TM', 'Turkmenistan'],
  ['TC', 'Turks And Caicos Islands'],
  ['TV', 'Tuvalu'],
  ['UG', 'Uganda'],
  ['UA', 'Ukraine'],
  ['AE', 'United Arab Emirates'],
  ['GB', 'United Kingdom'],
  ['US', 'United States'],
  ['UM', 'United States Minor Outlying Islands'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VU', 'Vanuatu'],
  ['VE', 'Venezuela'],
  ['VN', 'Vietnam'],
  ['VG', 'Virgin Islands, British'],
  ['VI', 'Virgin Islands, U.S.'],
  ['WF', 'Wallis And Futuna'],
  ['EH', 'Western Sahara'],
  ['YE', 'Yemen'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe']
]
